#!/usr/bin/env python3
"""Regenerate the "Supported TrueNAS versions" table in README.md from this
repository's ACTUAL published releases.

The releases are the source of truth for what is installable: a build is
published as a per-version release whose `.raw` asset the installer downloads.
Generating the table from the live releases list means it reflects both new
releases AND deletions automatically (a deleted release is simply absent from
the API), so the table is always right.

Reads the GitHub releases JSON array on stdin and rewrites, in place, the block
between the `<!-- BEGIN supported-versions ... -->` and `<!-- END
supported-versions -->` markers in the README file given as argv[1].

Usage (see .github/workflows/update-supported-versions.yml):
    gh api "repos/${GITHUB_REPOSITORY}/releases?per_page=100" \
        | .github/scripts/gen-supported-versions.py README.md
"""
import json
import re
import sys

BEGIN_PREFIX = "<!-- BEGIN supported-versions"
BEGIN_LINE = ("<!-- BEGIN supported-versions (auto-generated by "
              ".github/workflows/update-supported-versions.yml — do not edit by hand) -->")
END_MARK = "<!-- END supported-versions -->"

# Parsed out of the release body that build.yml renders. The header and the
# "Target kernel" row are identical across the sibling sysexts; the driver row
# label differs (Gasket driver / HailoRT driver / MemryX SDK), so match any.
HDR_RE = re.compile(r"for TrueNAS SCALE (.+?) \((.+?)\)")
KER_RE = re.compile(r"Target kernel\s*\|\s*`([^`]+)`")
DRV_RE = re.compile(r"\|\s*(Gasket driver|HailoRT driver|MemryX SDK)\s*\|\s*`([^`]+)`")
# Fallback when a release body is not in the standard format: pull the TrueNAS
# version out of the tag (vX-<drivertoken>...). The version itself may contain
# dashes (26.0.0-BETA.2), so stop at the first known driver token.
TAG_VER_RE = re.compile(r"^v(.+?)-(?:gasket|hailo|hailort|memryx)", re.IGNORECASE)


def truenas_sort_key(version):
    """Order TrueNAS versions: numeric base, then BETA < RC < final, then num."""
    base, _, pre = version.partition("-")
    bp = [int(p) if p.isdigit() else 0 for p in base.split(".")]
    if not pre:
        return (bp, 3, 0)  # a final release sorts above its BETA/RC
    typ, _, num = pre.partition(".")
    rank = {"BETA": 0, "RC": 1}.get(typ.upper(), 2)
    return (bp, rank, int(num) if num.isdigit() else 0)


def main():
    if len(sys.argv) != 2:
        print("usage: gen-supported-versions.py <README.md>", file=sys.stderr)
        sys.exit(2)
    readme_path = sys.argv[1]

    data = json.load(sys.stdin)
    if isinstance(data, dict):  # an API error object, not a list
        print(f"ERROR: GitHub API returned: {data.get('message', data)!r}", file=sys.stderr)
        sys.exit(1)
    if len(data) >= 100:
        # per_page=100 without pagination; surface possible truncation loudly
        # rather than silently dropping older releases from the table.
        print("WARNING: 100 releases returned; table may be truncated. Add pagination.",
              file=sys.stderr)

    # One row per distinct TrueNAS version: keep the newest release for it.
    by_version = {}
    for r in data:
        if r.get("draft"):
            continue
        tag = r.get("tag_name", "")
        body = r.get("body") or ""
        hdr = HDR_RE.search(body)
        if hdr:
            version, train = hdr.group(1).strip(), hdr.group(2).strip()
        else:
            tm = TAG_VER_RE.match(tag)
            if not tm:
                continue  # cannot identify the TrueNAS version; skip it
            version, train = tm.group(1), ""
        ker = KER_RE.search(body)
        drv = DRV_RE.search(body)
        published = r.get("published_at") or r.get("created_at") or ""
        entry = {
            "version": version,
            "train": train,
            "kver": ker.group(1) if ker else "",
            # "Gasket driver" -> "Gasket 1.0-18.4"; "MemryX SDK" -> "MemryX SDK 2.1"
            "driver": f"{drv.group(1).replace(' driver', '')} {drv.group(2)}" if drv else "",
            "prerelease": bool(r.get("prerelease")),
            "tag": tag,
            "url": r.get("html_url", ""),
            "published": published,
        }
        cur = by_version.get(version)
        if cur is None or published > cur["published"]:
            by_version[version] = entry

    rows = list(by_version.values())
    stable = sorted((x for x in rows if not x["prerelease"]),
                    key=lambda x: truenas_sort_key(x["version"]), reverse=True)
    preview = sorted((x for x in rows if x["prerelease"]),
                     key=lambda x: truenas_sort_key(x["version"]), reverse=True)

    def row(x, channel):
        ver = x["version"] + (f" ({x['train']})" if x["train"] else "")
        ker = f"`{x['kver']}`" if x["kver"] else "—"
        drv = x["driver"] or "—"
        rel = f"[`{x['tag']}`]({x['url']})" if x["url"] else f"`{x['tag']}`"
        return f"| {channel} | {ver} | {ker} | {drv} | {rel} |"

    table = [
        "| Channel | TrueNAS version | Kernel | Driver | Release |",
        "| --- | --- | --- | --- | --- |",
    ]
    table += [row(x, "Stable") for x in stable]
    table += [row(x, "Preview (beta)") for x in preview]
    if not stable and not preview:
        table.append("| _none_ | _no published releases yet_ | — | — | — |")

    block = BEGIN_LINE + "\n" + "\n".join(table) + "\n" + END_MARK

    text = open(readme_path, encoding="utf-8").read()
    start = text.find(BEGIN_PREFIX)
    end = text.find(END_MARK)
    if start == -1 or end == -1:
        print(f"ERROR: supported-versions markers not found in {readme_path}", file=sys.stderr)
        sys.exit(1)
    end += len(END_MARK)
    new = text[:start] + block + text[end:]
    if new != text:
        open(readme_path, "w", encoding="utf-8").write(new)
        print(f"{readme_path}: supported-versions table updated "
              f"({len(stable)} stable, {len(preview)} preview)")
    else:
        print(f"{readme_path}: supported-versions table unchanged")


if __name__ == "__main__":
    main()
