#!/usr/bin/env python3
"""Regenerate the "Supported TrueNAS versions" table in README.md.

The table is kernel-keyed. A sysext's kernel modules bind to the exact
kernel string (uname -r / vermagic), and many TrueNAS point releases ship
the same kernel, so one build covers a whole range of versions. Rows come
from two sources:

  * .github/kernel-map.json (maintained by gen-kernel-map.py from the
    rootfs.mtree manifests on download.truenas.com): which TrueNAS versions
    ship which kernel.
  * This repository's published releases (GitHub releases JSON array on
    stdin): which kernels have an installable build, and which release the
    installer serves for them.

A kernel with no release still gets a row: "not built yet" when no build
exists, or the unpromoted build's tag marked "awaiting hardware-test
promotion" when one is gated behind verification. A preview (beta) version
likewise names its newest build approved for its train, or else the newest
build marked "awaiting hardware test": the installer serves nothing
unapproved on any channel. The table is a complete coverage map instead of a
list of what happens to exist.

Usage (see .github/workflows/update-supported-versions.yml):
    gh api "repos/${GITHUB_REPOSITORY}/releases?per_page=100" \
        | gen-supported-versions.py README.md .github/kernel-map.json
"""
import json
import re
import sys

BEGIN_PREFIX = "<!-- BEGIN supported-versions"
BEGIN_LINE = ("<!-- BEGIN supported-versions (auto-generated by "
              ".github/workflows/update-supported-versions.yml - do not edit by hand) -->")
END_MARK = "<!-- END supported-versions -->"

# Parsed out of the release body that build.yml renders. The header and the
# "Target kernel" row are identical across the sibling sysexts; the driver row
# label differs (Gasket driver / HailoRT driver / MemryX SDK), so match any.
HDR_RE = re.compile(r"for TrueNAS SCALE (.+?) \((.+?)\)")
KER_RE = re.compile(r"Target kernel\s*\|\s*`([^`]+)`")
DRV_RE = re.compile(r"\|\s*(Gasket driver|HailoRT driver|MemryX SDK)\s*\|\s*`([^`]+)`")
# Fallback when a release body is not in the standard format: pull the TrueNAS
# version out of the tag (vX-<drivertoken>...). The version itself may contain
# dashes (26.0.0-BETA.2), so stop at the first known driver token.
TAG_VER_RE = re.compile(r"^v(.+?)-(?:gasket|hailo|hailort|memryx)", re.IGNORECASE)
# Kernel-keyed tags encode the short kernel (k6.12.91-gasket1.0-18.4-r3):
# the only kernel signal left when a body lost its rows.
KTAG_KVER_RE = re.compile(r"^k(\d+(?:\.\d+)*)-(?:gasket|hailo|hailort|memryx)",
                          re.IGNORECASE)
# The line promote.yml appends to a release's notes when a hardware test on a
# train signs the build off (the installer's pattern).
VERIFIED_RE = re.compile(r"^[ \t]*<!--\s*verified-train:\s*([^\s>]+?)\s*-->", re.M)


def train_key(version):
    """Train key of a TrueNAS version, the installer's rule: the major
    version from 26 on (every 26.x release, betas included, is one train),
    major.minor before that. '' when the version has none."""
    major, dot, rest = version.partition(".")
    if not major.isdigit():
        return ""
    if int(major) >= 26:
        return major
    minor = re.match(r"[0-9]*", rest).group(0)
    return major + "." + minor if dot and minor else ""


def truenas_sort_key(version):
    """Order TrueNAS versions: numeric base, then BETA < RC < final, then num."""
    base, _, pre = version.partition("-")
    bp = [int(p) if p.isdigit() else 0 for p in base.split(".")]
    if not pre:
        return (bp, 3, 0)  # a final release sorts above its BETA/RC
    typ, _, num = pre.partition(".")
    rank = {"BETA": 0, "RC": 1}.get(typ.upper(), 2)
    return (bp, rank, int(num) if num.isdigit() else 0)


def is_preview_version(version):
    """A BETA/RC TrueNAS version is the preview channel; matches how install.sh
    classifies the running version (so the table's channel and the installer's
    behaviour can never disagree)."""
    return bool(re.search(r"-(?:BETA|RC)", version, re.IGNORECASE))


def parse_releases(data):
    """GitHub releases JSON array -> {version: [entry, ...]}, drafts skipped."""
    releases_by_version = {}
    for r in data:
        if r.get("draft"):
            continue
        tag = r.get("tag_name", "")
        body = r.get("body") or ""
        hdr = HDR_RE.search(body)
        if hdr:
            version, train = hdr.group(1).strip(), hdr.group(2).strip()
        else:
            tm = TAG_VER_RE.match(tag)
            if tm:
                version, train = tm.group(1), ""
            elif KTAG_KVER_RE.match(tag):
                # No TrueNAS version to key on, but the tag names the kernel;
                # resolve_ktag_kernels() fills kver in from it.
                version, train = "", ""
            else:
                # A release the table cannot identify (edited body, free-form
                # manual publish) still gets served by install.sh's kernel
                # match, so a silent skip makes the table lie. Warn loudly in
                # the workflow log instead.
                print(f"WARNING: cannot identify a TrueNAS version for "
                      f"release {tag}; it will not appear in the table",
                      file=sys.stderr)
                continue
        ker = KER_RE.search(body)
        drv = DRV_RE.search(body)
        km = KTAG_KVER_RE.match(tag)
        releases_by_version.setdefault(version, []).append({
            "version": version,
            "train": train,
            "kver": ker.group(1) if ker else "",
            "kshort": km.group(1) if km else "",
            # "Gasket driver" -> "Gasket 1.0-18.4"; "MemryX SDK" -> "MemryX SDK 2.1"
            "driver": f"{drv.group(1).replace(' driver', '')} {drv.group(2)}" if drv else "",
            "prerelease": bool(r.get("prerelease")),
            "trains": sorted(set(VERIFIED_RE.findall(body))),
            "tag": tag,
            "url": r.get("html_url", ""),
            "published": r.get("published_at") or r.get("created_at") or "",
        })
    return releases_by_version


def resolve_ktag_kernels(releases_by_version, kernel_map):
    """Recover the full kernel string for k-tagged releases whose body lost
    the Target kernel row, via the kernel map, so they fill their kernel row
    instead of showing "not built yet" while install.sh serves them. Only
    promoted releases resolve: an unpromoted lost-body k-tag cannot be told
    apart from a preview build (check-kernel-coverage.py, same rule)."""
    full_by_short = {}
    for train_versions in (kernel_map.get("trains") or {}).values():
        for kver in train_versions.values():
            full_by_short[kver.split("-")[0]] = kver
    for rels in releases_by_version.values():
        for r in rels:
            if r["kver"] or not r["kshort"] or r["prerelease"]:
                continue
            full = full_by_short.get(r["kshort"], "")
            if full:
                r["kver"] = full
            elif not r["version"]:
                print(f"WARNING: release {r['tag']} has no Target kernel row "
                      f"and its tag kernel {r['kshort']} is not in the kernel "
                      "map; it will not appear in the table", file=sys.stderr)


def served_releases(releases_by_version):
    """The one release install.sh serves per version:
      * Preview (BETA/RC) versions -> newest release a hardware test approved
        for the version's train (a verified-train line in its notes; a
        preview build is approved only by that line, full release or not).
        With none approved, the newest build is still listed, flagged
        "pending": nothing installs it until its test signs it off.
      * Stable versions -> newest PROMOTED (non-prerelease) release. An
        unverified prerelease-only stable build is not auto-installable (it is
        gated behind hardware-test promotion), so it is omitted until then."""
    stable, preview = {}, {}
    for version, rels in releases_by_version.items():
        if not version:
            continue  # lost-body k-tags only feed kernel_winners
        rels.sort(key=lambda x: x["published"], reverse=True)
        if is_preview_version(version):
            approved = [x for x in rels if train_key(version) in x["trains"]]
            preview[version] = approved[0] if approved else dict(rels[0], pending=True)
        else:
            promoted = [x for x in rels if not x["prerelease"]]
            if promoted:
                stable[version] = promoted[0]
    return stable, preview


def version_range(versions):
    vs = sorted(versions, key=truenas_sort_key)
    return vs[0] if len(vs) == 1 else f"{vs[0]} - {vs[-1]}"


def newest_per_kernel(releases_by_version, want_prerelease):
    """Newest kernel-advertising release per kernel on the stable channel,
    keyed by promotion state. Preview (BETA/RC) builds never count: they are
    a separate channel and must never fill a stable kernel slot."""
    newest = {}
    for rels in releases_by_version.values():
        for r in rels:
            if (r["prerelease"] != want_prerelease or not r["kver"]
                    or is_preview_version(r["version"])):
                continue
            key = (r["kver"], r["train"])
            cur = newest.get(key)
            if cur is None or r["published"] > cur["published"]:
                newest[key] = r
    return newest


def for_train(newest, kver, train):
    """The release install.sh serves for (kernel, train): its train guard
    refuses cross-train matches, and a release with no header train passes
    everywhere (lost-body k-tags, same rule as the installer)."""
    best = None
    for (k, t), r in newest.items():
        if k != kver or (t and t != train):
            continue
        if best is None or r["published"] > best["published"]:
            best = r
    return best


def kernel_winners(releases_by_version):
    """The release install.sh serves per advertised kernel: the newest
    promoted (non-prerelease) release whose body records that kernel,
    whichever TrueNAS version produced it. The table must name this release
    on a kernel row, not the row versions' own newest build, or the table
    and the installer disagree the moment a sibling rebuild lands."""
    return newest_per_kernel(releases_by_version, want_prerelease=False)


def pending_builds(releases_by_version):
    """The newest unpromoted stable build per kernel: a prerelease from a
    non-BETA/RC version, still gated behind hardware-test promotion. The
    installer's error message tells the user such a build exists and installs
    once promoted; the table must say the same instead of "not built yet"."""
    return newest_per_kernel(releases_by_version, want_prerelease=True)


def build_rows(stable, preview, kernel_map, winners, pending=None):
    """One row per train's known stable kernel (built or not), then stable
    releases the kernel match cannot serve (single-version rows), then
    preview releases."""
    pending = pending or {}
    by_kernel = {}
    mapped_versions = set()
    for train, train_versions in (kernel_map.get("trains") or {}).items():
        for version, kver in train_versions.items():
            by_kernel.setdefault((train, kver), []).append(version)
            mapped_versions.add(version)

    keyed = []
    for (train, kver), versions in by_kernel.items():
        for v in versions:
            r = stable.get(v)
            if r and r["kver"] and r["kver"] != kver:
                print(f"WARNING: release {r['tag']} records kernel {r['kver']} "
                      f"but the kernel map says {kver} for {v}", file=sys.stderr)
        r = for_train(winners, kver, train)
        p = for_train(pending, kver, train) if r is None else None
        keyed.append((max(truenas_sort_key(v) for v in versions), {
            "channel": "Stable", "kver": kver,
            "versions": version_range(versions),
            "driver": r["driver"] if r else (p["driver"] if p else ""),
            "tag": r["tag"] if r else "",
            "url": r["url"] if r else "",
            "pending_tag": p["tag"] if p else "",
            "pending_url": p["url"] if p else ""}))

    for version, r in stable.items():
        if not r["kver"]:
            # A legacy release without a Target kernel row only installs on
            # its exact version (install.sh's fallback), so it keeps its own
            # row naming itself no matter what the map says.
            keyed.append((truenas_sort_key(version), {
                "channel": "Stable", "kver": "", "versions": version,
                "driver": r["driver"], "tag": r["tag"], "url": r["url"]}))
        elif version not in mapped_versions:
            # A version the map does not know (older train, or a listing gap)
            # keeps its own row so it never drops off, but it names the
            # release the installer would deliver for its kernel.
            w = for_train(winners, r["kver"], r["train"]) or r
            keyed.append((truenas_sort_key(version), {
                "channel": "Stable", "kver": r["kver"], "versions": version,
                "driver": w["driver"], "tag": w["tag"], "url": w["url"]}))

    keyed.sort(key=lambda t: t[0], reverse=True)
    rows = [row for _, row in keyed]

    for version in sorted(preview, key=truenas_sort_key, reverse=True):
        r = preview[version]
        if r.get("pending"):
            rows.append({"channel": "Preview (beta)", "kver": r["kver"],
                         "versions": version, "driver": r["driver"],
                         "tag": "", "url": "",
                         "pending_tag": r["tag"], "pending_url": r["url"],
                         "pending_note": "awaiting hardware test"})
            continue
        rows.append({"channel": "Preview (beta)", "kver": r["kver"],
                     "versions": version, "driver": r["driver"],
                     "tag": r["tag"], "url": r["url"]})
    return rows


def render_table(rows):
    lines = ["| Channel | Kernel | TrueNAS versions | Driver | Release |",
             "| --- | --- | --- | --- | --- |"]
    if not rows:
        lines.append("| _none_ | - | _no data yet_ | - | - |")
    for row in rows:
        ker = f"`{row['kver']}`" if row["kver"] else "-"
        if row["url"]:
            rel = f"[`{row['tag']}`]({row['url']})"
        elif row["tag"]:
            rel = f"`{row['tag']}`"
        elif row.get("pending_tag"):
            pt = (f"[`{row['pending_tag']}`]({row['pending_url']})"
                  if row.get("pending_url") else f"`{row['pending_tag']}`")
            rel = f"{pt} _({row.get('pending_note', 'awaiting hardware-test promotion')})_"
        else:
            rel = "_not built yet_"
        drv = row["driver"] or "-"
        lines.append(f"| {row['channel']} | {ker} | {row['versions']} | {drv} | {rel} |")
    return lines


def read_releases(text):
    """Parse `gh api --paginate` output: one JSON array per page,
    concatenated. An API error object aborts."""
    decoder = json.JSONDecoder()
    data = []
    pos = 0
    while pos < len(text):
        if text[pos].isspace():
            pos += 1
            continue
        doc, pos = decoder.raw_decode(text, pos)
        if isinstance(doc, dict):
            print(f"ERROR: GitHub API returned: {doc.get('message', doc)!r}",
                  file=sys.stderr)
            sys.exit(1)
        data.extend(doc)
    return data


def main():
    if len(sys.argv) not in (2, 3):
        print("usage: gen-supported-versions.py <README.md> [kernel-map.json]",
              file=sys.stderr)
        sys.exit(2)
    readme_path = sys.argv[1]

    kernel_map = {}
    if len(sys.argv) == 3:
        try:
            with open(sys.argv[2], encoding="utf-8") as f:
                kernel_map = json.load(f)
        except FileNotFoundError:
            print(f"WARNING: {sys.argv[2]} not found; table lists released "
                  "versions only", file=sys.stderr)

    data = read_releases(sys.stdin.read())

    parsed = parse_releases(data)
    resolve_ktag_kernels(parsed, kernel_map)
    stable, preview = served_releases(parsed)
    rows = build_rows(stable, preview, kernel_map, kernel_winners(parsed),
                      pending_builds(parsed))
    table = render_table(rows)

    block = BEGIN_LINE + "\n" + "\n".join(table) + "\n" + END_MARK

    text = open(readme_path, encoding="utf-8").read()
    start = text.find(BEGIN_PREFIX)
    end = text.find(END_MARK)
    if start == -1 or end == -1:
        print(f"ERROR: supported-versions markers not found in {readme_path}",
              file=sys.stderr)
        sys.exit(1)
    end += len(END_MARK)
    new = text[:start] + block + text[end:]
    if new != text:
        open(readme_path, "w", encoding="utf-8").write(new)
        print(f"{readme_path}: supported-versions table updated ({len(rows)} rows)")
    else:
        print(f"{readme_path}: supported-versions table unchanged")


if __name__ == "__main__":
    main()
